### ISSUE TITLE
Dependency Management?

### ISSUE THREAD

**Issue by rberger** [aerofs/gockerize#1]
The readme says:

> Relying on this feature should be avoided in favor of vendored dependencies.

What do you recommend to do that?

**Comment by huguesb** [comment]
It is outside the scope of this tool to make specific recommendations on _how_ to vendor dependencies.

The upcoming Go 1.5 is supposed to improve the vendoring story but the community also came up with a few tools to address this issue. One that looks particularly interesting is [gb](http://getgb.io/) and we might consider integrating it into gockerize at some point in the future.

In the meantime, it is also possible to avoid vendoring dependencies by simply broadening the build context to your entire `GOPATH`.

For instance, say you have the following hierarchy:

```
src/
    github.com/
        foo/
            bar/
    acme.com/
        baz/
```

Where `acme.com/baz` is the service you want to dockerize and it depends on `github.com/foo/bar`

You can invoke dockerize as follows (from `src/acme.com/baz`):

```
dockerize baz acme.com/baz ../..
```
